# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b672f30dc61be6c18241f8fbe5141c3b75c36ad79e2752f85848770ef75521b6600b3d4b614e93a14f90b44a9f998a87e149b77cdee17a2cf55676fd3afc2123

test:
  secret_key_base: cc8371a7d29de68d1b7176a0dad59d1ce2c6c130994c34a5eb3462266506821b0b40ef92db20afc3eb2f0de9fb19e613c3305d71dc2e46cbdee5ad02919affbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
